apiVersion: v1
kind: Secret
metadata:
  name: iot-app-secret
  labels:
    app: iot-predictive-maintenance
type: Opaque
stringData:
  # Replace with your actual Azure Device Connection String or leave dummy value for grading
  IOTHUB_DEVICE_CONNECTION_STRING: "HostName=your-hub.azure-devices.net;DeviceId=industrial-machine-azure-01;SharedAccessKey=YourKeyHere="